---
- hosts: all
  become: true
  
  tasks:
  - name: Mencoba mengonversi file webapp.war menjadi image docker
    command: docker build -t devops-image-v3 .
    args:
      chdir: /opt/docker
  
  - name: Mencoba membuat container dari image 
    command: docker run -d --name devops-container-v3 -p 8080:8080 devops-image-v3
