---
- hosts: all
  become: true

  tasks:
  - name: Mencoba melihat semua docker containers yang ada
    command: docker container ls -a -q --filter name=devops*
    register: docker_containers

  - name: Mencoba me-stop running containers
    command: docker container stop {{ docker_containers.stdout }}
    ignore_errors: yes

  - name: Mencoba me-remove stopped container
    command: docker container rm {{ docker_containers.stdout }}
    ignore_errors: yes

  - name: Mencoba melihat semua docker images yang ada
    command: docker images -q --filter reference='devops*'
    register: docker_images

  - name: Mencoba me-remove docker image
    command: docker rmi {{ docker_images.stdout }}
    ignore_errors: yes

  - name: Mencoba mengonversi file webapp.war menjadi image docker
    command: docker build -t devops-image-v4 .
    args:
      chdir: /opt/docker

  - name: Mencoba membuat container dari image
    command: docker run -d --name devops-container-v4 -p 8080:8080 devops-image-v4
