---
- hosts: all
  become: true
  
  tasks:
 - name: Mencoba me-stop running containers
   command: docker container stop $(docker container ls -q --filter name=v*)
   ignore_errors: yes
		
  - name: Mencoba me-remove stopped container
    command: docker container rm $(docker container ls -q --filter name=v*)
    ignore_errors: yes	
	
  - name: Mencoba me-remove docker image
    command: docker rmi $(docker images --filter=reference='v*') 
    ignore_errors: yes 

  - name: Mencoba mengonversi file webapp.war menjadi image docker
    command: docker build -t v2_image .
    args:
      chdir: /opt/docker
  
  - name: Mencoba membuat container dari image 
    command: docker run -d --name v2_container -p 8080:8080 v2_image
